
name: 'aes_dbt'
version: '1.0.0'

# project name.
profile: 'aes_dbt'

model-paths: ["models"]
test-paths: ["tests"]

# `dbt clean`実行時にクリアされる
clean-targets:         
  - "target"
  - "dbt_packages"

models:
  aes_dbt:
      +materialized: view
